import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import { fetchCoffeeStores } from "../lib/coffee-stores";
import { createApi } from "unsplash-js";

const unsplash = createApi({
  accessKey: "nnAIlIg6FIWJD2PPzH-sQtIluKeDj7NmbC1uaNqa3zE",
  
})

export async function getStaticProps() {
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home(props) {
  // api.search
  //   .getPhotos({ query: "coffee" })
  //   .then((result) => {
  //     const coffeeData = result;
  //     console.log(coffeeData.response.results[0].urls.full);
  //   })
  //   .catch(() => {
  //     console.log("something went wrong!");
  //   });

  console.log("props", props);
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner className={styles.Banner} />
        {props.coffeeStores.length > 0 ? (
          <h2 className={styles.heading2}>Middleton Coffee Stores</h2>
        ) : null}
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
            return (
              <Card
                key={coffeeStore.fsq_id}
                name={coffeeStore.name}
                imgUrl={
                   coffeeStore.imgUrl ||
                  "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                }
                href={`/coffee-store/${coffeeStore.fsq_id}`}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
