import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";

import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  console.log("hi getStaticProps");
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home(props) {
  console.log("props", props);
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner className={styles.Banner} />
        {props.coffeeStores.length > 0 ? (
          <h2 className={styles.heading2}>Middleton Coffee Stores</h2>
        ) : null}
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStores) => {
            return (
              <Card
                key={coffeeStores.id}
                name={coffeeStores.name}
                imgUrl={coffeeStores.imgUrl}
                href={`/coffee-store/${coffeeStores.id}`}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
